name: Build & Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create build folder
        run: mkdir -p build

      - name: Create ZIP package
        run: |
          zip -r build/${{ github.event.repository.name }}-${{ github.ref_name }}.zip . \
            -x "*.git*" \
               ".github/*" \
               "tests/*" \
               "node_modules/*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
